### PR TITLE
Renamed field that specifies adapted type

### PR DESCRIPTION
**Pull request by anmenaga**
# PR Summary

Previously, when an adapter process is invoked (for the `dsc resource ...` command) the actual resource type name is added to the input JSON bag as a *special* `type` field.
This results in collisions if resource has an actual `type` property. (e.g. `PSDesiredStateConfiguration/File` resource)

This PR renames the *special* field in the json to `adapted_dsc_type` which is less likely to cause collisions.

### CODE REVIEW

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Please add a test

**Comment by anmenaga** [comment]
> Please add a test

This is already greatly covered by existing tests. Every non-List PSAdapter operation uses this code path.

**Comment by SteveL-MSFT** [comment]
> > Please add a test
> 
> This is already greatly covered by existing tests. Every non-List PSAdapter (and other adapters) operation uses this code path.

But we don't have an explicit test to verify the behavior otherwise it would have failed before this change

**Comment by anmenaga** [comment]
Added tests and a test adapter that verifies the renamed field.

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
